import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Homepage from "~/components/Homepage/Homepage";
import Navbar from "~/components/Navbar/Navbar";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Xoltan Marketplace Store</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <Homepage/>
      </main>
    </>
  );
};

export default Home;
